title: <a href="https://distortedsignal.github.io/">distortedsignal This Time, It's Personal</a>
description: Ramblings, coherent and otherwise.
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
